AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'vendor/bundle/**/*'
    - 'spec/**/*'
Style/DoubleNegation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/EmptyComment:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 20
Metrics/LineLength:
  IgnoredPatterns:
    - 'warn'
    - 'puts'
    - 'raise'
Style/RedundantSelf:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
